### PR TITLE
[CI/CD] Add clang-format workflow

### LINKED ISSUE #2: [Feature] Setup clang-format linting for Pull Requests
I feel it's important to keep the coding style concise. While this can be done moderately well by hand, IMO it's better if there is an automated sanity check.

## **Proposal**

I'd like an automatic check that uses the `.clang-format` file to scan/lint (not sanitize, as there might be exceptions) all submitted files in a PR.

### PR DESCRIPTION
**Pull request by ByteOtter**
## What?

Add a `clang-format` workflow to the repo to check for code style using the existing `.clang-format` file.

This PR uses [this existing workflow](https://github.com/marketplace/actions/clang-format-check) to improve and enforce code quality.

## Links

Fixes: #2 
Tracks: N/A

### CODE REVIEW

**Comment by ByteOtter** [comment]
@marv7000 looks like your .clang-format file was not correct, so I adjusted it according to my language server suggestions. The checks still fail though, because $REASON.

**Comment by marv7000** [comment]
Yea, I kind of just glossed over the docs for it. It fails because of "VariableCase" not being a key

**Comment by marv7000** [comment]
You might have to just nuke the case and comment style blocks at the end, since they don't seem to exist

**Comment by ByteOtter** [comment]
Yeah let's just keep it running over the entire codebase. You gotta fix the warnings anyway or add 

```c
int formatted_code;
// clang-format off
    void    unformatted_code  ;
// clang-format on
void formatted_code_again;
```

According to https://clang.llvm.org/docs/ClangFormatStyleOptions.html

**Pull request merged**
